image: node:18

pipelines:
  branches:
    main:
      - step:
          name: Validate and Release
          script:
            - npm install
            - npx versionings validate --json
            - npx versionings release --semver=minor --branch=ci-release --push --ci --json
          caches:
            - node
