name: Release Branch

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - name: Validate
        run: npx versionings validate

      - name: Release
        run: npx versionings release --semver=minor --branch=ci-release --push --ci --json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
